name: Workflow for Build and Deployment

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Name of the Docker app"
        required: false
        default: "plane-tg-bot-app"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: "Lint code with flake8"
        continue-on-error: true
        run: |
          flake8 api.py bot.py main.py --max-line-length=88 || echo "WARNING: bad code"

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and tag Docker image"
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ github.event.inputs.app_name }}:latest .

      - name: "Push Docker image to GitHub Container Registry"
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ github.event.inputs.app_name }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: "Decode SSH private key"
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > id_rsa
          chmod 600 id_rsa

      - name: "Deploy to Virtual Machine via Jump Host"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: id_rsa
          proxy_jump: ${{ secrets.SSH_PROXY_JUMP }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}/${{ github.event.inputs.app_name }}:latest
            docker stop ${{ github.event.inputs.app_name }} || true
            docker rm ${{ github.event.inputs.app_name }} || true
            docker run -d \
              --name ${{ github.event.inputs.app_name }} \
              -p 8888:8888 \
              ghcr.io/${{ github.repository }}/${{ github.event.inputs.app_name }}:latest
  
